name       : cni-plugins
version    : 0.9.0
release    : 7
source     :
    - https://github.com/containernetworking/plugins/archive/v0.9.0.tar.gz : 54abd2fb7762943ff57832dfba19de12db09f0a0f8e69b31f1a2bb2baca395e7
license    : Apache-2.0
component  : virt
summary    : Some standard networking plugins, maintained by the CNI (containernetworking) team.
description: |
    Main plugins - interface-creating: bridge, ipvlan, loopback, macvlan, ptp, vlan, host-device
    IPAM plugins - IP address allocation: dhcp, host-local, static
    Meta - other plugins: flannel, tuning, portmap, bandwidth sbr, firewall
builddeps  :
    - golang
build      : |
    ./build_linux.sh
install    : |
    pushd bin/
    install -Dm00755 -t $installdir/%libdir%/cni/ *
