name       : cni-plugins
version    : 1.0.1
release    : 11
source     :
    - https://github.com/containernetworking/plugins/archive/v1.0.1.tar.gz : 2ba3cd9f341a7190885b60d363f6f23c6d20d975a7a0ab579dd516f8c6117619
license    : Apache-2.0
component  : virt
summary    : Some standard networking plugins, maintained by the CNI (containernetworking) team.
description: |
    Main plugins - interface-creating: bridge, ipvlan, loopback, macvlan, ptp, vlan, host-device
    IPAM plugins - IP address allocation: dhcp, host-local, static
    Meta - other plugins: flannel, tuning, portmap, bandwidth sbr, firewall
builddeps  :
    - golang
build      : |
    ./build_linux.sh
install    : |
    pushd bin/
    install -Dm00755 -t $installdir/%libdir%/cni/ *
