name       : cni-plugins
version    : 0.8.2
release    : 1
source     :
    - https://github.com/containernetworking/plugins/archive/v0.8.2.tar.gz : 91994d305a86a2c5a70e9dd7add9e277074065678b605bf12983e6e43fdcd4d8
license    : Apache-2.0
component  : virt
summary    : Some standard networking plugins, maintained by the CNI (containernetworking) team.
description: |
    Main plugins - interface-creating: bridge, ipvlan, loopback, macvlan, ptp, vlan, host-device
    IPAM plugins - IP address allocation: dhcp, host-local, static
    Meta - other plugins: flannel, tuning, portmap, bandwidth sbr, firewall
builddeps  :
    - golang
build      : |
    ./build_linux.sh
install    : |
    pushd bin/
    install -Dm00755 -t $installdir/%libdir%/cni/ *
