name       : cni-plugins
version    : 0.8.5
release    : 4
source     :
    - https://github.com/containernetworking/plugins/archive/v0.8.5.tar.gz : 9d1526ed965ac6562fd95a931ab2346b3c5efd58c2f569038ba3c530f7e66472
license    : Apache-2.0
component  : virt
summary    : Some standard networking plugins, maintained by the CNI (containernetworking) team.
description: |
    Main plugins - interface-creating: bridge, ipvlan, loopback, macvlan, ptp, vlan, host-device
    IPAM plugins - IP address allocation: dhcp, host-local, static
    Meta - other plugins: flannel, tuning, portmap, bandwidth sbr, firewall
builddeps  :
    - golang
build      : |
    ./build_linux.sh
install    : |
    pushd bin/
    install -Dm00755 -t $installdir/%libdir%/cni/ *
